# Our runtime will be node
language: node_js
node_js:
  - 0.10

# Init a web server since we seem to need it for our tests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# blacklist
branches:
  except:
    - gh-pages

# whitelist
branches:
  only:
    - master